# this is all based on default of Nerd Fonts

# global / Prompt options
command_timeout = 1000

# this simulates right prompt, whitespace removed for desired formatting
format = "$all $fill $time$line_break$character"

[fill]
symbol = " "

[character]
success_symbol = "[\ueb70](dimmed blue)"
error_symbol = "[\ueb70](dimmed blue)"
# some symbol options: \ueb70 â–¶ Â» â¯ > â» \ue0bc \ueb6e
# some color options: (bold black) and (dimmed green)

# [nodejs]
# symbol = "[â¬¢](bold green) "

[time]
disabled = false

[shlvl]
disabled = false
format = '[$symbol$shlvl]($style) '
# format = '[$symbol]($style) '
# repeat = false # default
symbol = "\uf103" # ğŸš, â¯, ğŸª¹, ğŸªº, \uf103
# repeat_offset = 0 # default
# threshold = 2 # default
