# this is all based on default of Nerd Fonts

command_timeout = 1000

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ—](bold red)"

[time]
disabled = false

# [nodejs]
# symbol = "[â¬¢](bold green) "

[shlvl]
disabled = false
format = '[$symbol$shlvl]($style) '
# format = '[$symbol]($style) '
# repeat = false # default
symbol = "\uf103" # ğŸš, â¯, ğŸª¹, ğŸªº, \uf103
# repeat_offset = 0 # default
# threshold = 2 # default
